package com.lisasoft.ows6.validator;

/**
 * This this class of exceptions if thrown during the validation
 * (e.g., Schematron validation) of a server response during testing.
 * 
 * @author shansen
 *
 */
public class ValidationError extends Error {

	/**
	 * serialVersionUID generated by Eclipse
	 */
	private static final long serialVersionUID = -7389147347115876624L;


	/**
	 * Auto-generated constructor stub
	 */
	public ValidationError() {
		super();
	}

	
	/**
	 * Auto-generated constructor stub
	 */
	public ValidationError(String arg0, Throwable arg1) {
		super(arg0, arg1);
	}

	
	/**
	 * Auto-generated constructor stub
	 */
	public ValidationError(String arg0) {
		super(arg0);
	}

	
	/**
	 * Auto-generated constructor stub
	 */
	public ValidationError(Throwable arg0) {
		super(arg0);
	}

	

}
