/*
 *    DuckHawk provides a Performance Testing framework for load
 *    testing applications and web services in an automated and
 *    continuous fashion.
 * 
 *    http://docs.codehaus.org/display/DH/Home
 * 
 *    Copyright (C) 2008 LISAsoft- http://www.lisasoft.com.
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation;
 *    version 2.1 of the License.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 */

package com.lisasoft.wfsvalidator.validator;

/**
 * This this class of exceptions if thrown during the validation
 * (e.g., Schematron validation) of a server response during testing.
 * 
 * @author shansen
 *
 */
public class ValidationError extends Error {

	/**
	 * serialVersionUID generated by Eclipse
	 */
	private static final long serialVersionUID = -7389147347115876624L;


	/**
	 * Auto-generated constructor stub
	 */
	public ValidationError() {
		super();
	}

	
	/**
	 * Auto-generated constructor stub
	 */
	public ValidationError(String arg0, Throwable arg1) {
		super(arg0, arg1);
	}

	
	/**
	 * Auto-generated constructor stub
	 */
	public ValidationError(String arg0) {
		super(arg0);
	}

	
	/**
	 * Auto-generated constructor stub
	 */
	public ValidationError(Throwable arg0) {
		super(arg0);
	}

	

}
